[package]
name = "kerkers_en_draken"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = {version = "0.37.2", features = ["serialize"] }
rand = "0.8.5"
serde = {version = "1.0.217", features = ["derive"] }
sqlite = "0.36.1"
